[technote]
id = "SITCOMTN-110"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-110.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-110"
github_default_branch = "main"
date_created = 2024-02-05T16:15:36Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Parker"
name.family = "Fagrelius"
internal_id = "fagreliusp"

[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
